[tool.poetry]
name = "NLP_Project"
version = "0.1.0"
description = ""
authors = ["Janosch Hoefer"]

[tool.poetry.scripts]
main = "src.NLP_Project.main:main"

[tool.poetry.dependencies]
python = "^3.10"
transformers = {extras = ["sentencepiece"], version = "^4.23.1"}
torch = "^1.12.1"
torchvision = "^0.13.1"
torchaudio = "^0.12.1"
ipywidgets = "^8.0.2"
tqdm = "^4.64.1"
mkl = "^2022.2.0"
mkl-include = "^2022.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"
black = "^22.1.0"
flake8 = "^4.0.1"
pre-commit = "^2.17.0"
ipykernel = "^6.16.0"

[build-system]
requires = ["poetry-core>=1.2.2"]
build-backend = "poetry.core.masonry.api"
