name: Integration
on:
  pull_request:
    branches:
      - develop
      - qa
      - production
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #  ----- Check-out repo and check dependencies
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check dependencies
        run: ./.github/helper_scripts/trivy_dependencies_check.sh
        shell: bash

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.X"

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #  -----  Install ubuntu dependencies  -----
      #----------------------------------------------
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --without SpaCy,Visuals
          python --version

      - name: Run linter
        run: |
          make lint
